name: learn_flutter_docs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/03_layout/01_overview/02_row_column_many_widget/images/
    - lib/03_layout/01_overview/03_container/images/
    - lib/03_layout/01_overview/04_grid_and_view/images/
    - lib/03_layout/01_overview/05_grid_list_demo/images/
    - lib/03_layout/01_overview/06_grid_and_list/images/
    - lib/03_layout/01_overview/08_card_and_stack/images/
    - lib/03_layout/01_overview/09_bottom_navigation_demo/images/
    - lib/03_layout/01_overview/10_cards_demo/images/
    - lib/03_layout/03_layout_tutorial/images/
    - lib/03_layout/05_scrolling/03_floating_app_bar/images/
    - lib/03_layout/05_scrolling/04_parallax_scrolling/images/
